spring.application.name=product-microservice
server.port = 8091
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/productdb

# OpenAPI / Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
# springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.show-extensions=true
springdoc.default-flat-param-object=true