-- MYSQL
CREATE TABLE users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    ROLE VARCHAR(100),
    STATUS VARCHAR(100),
    CREATED_AT DATE,
    UPDATED_AT DATE
);

-- POSTGRES
CREATE TABLE users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(100) DEFAULT 'USER',
    status VARCHAR(100) DEFAULT 'ACTIVE',
    created_at DATE,
    updated_at DATE
);

CREATE TABLE products (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(200),
    price NUMERIC(10,2) NOT NULL,
    stock INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at DATE,
    updated_at DATE
);